#!/bin/sh -e

[ -d .git ] || exit

YEAR=2023
URL="https://adventofcode.com/$YEAR/day/$1/input"
if [ "$1" -lt 10 ]; then
  OUTDIR="0${1}"
else
  OUTDIR="${1}"
fi
[ -d $OUTDIR ] ||  { echo "Day $1 does not exist. Making directory..."  && command mkdir -v $OUTDIR ;}

printf "Downloding + Preview of first few lines...\n\n"
curl "$URL" --cookie "session=$AOC_SESSION" --silent --output-dir "$OUTDIR" --output input.txt
